root -l -b -q 'HbbHbb_KinematicSelection.cc+("Signal_V42_V8", "glugluToX300ToHHTobbbb_8TeV_width1MeV_FASTSIM_PU", "PUWeight.root")'
root -l -b -q 'HbbHbb_KinematicSelection.cc+("Signal_V42_V8", "glugluToX400ToHHTobbbb_8TeV_width1MeV_FASTSIM_PU", "PUWeight.root")'
root -l -b -q 'HbbHbb_KinematicSelection.cc+("Signal_V42_V8", "glugluToX500ToHHTobbbb_8TeV_width1MeV_FASTSIM_PU", "PUWeight.root")'
root -l -b -q 'HbbHbb_KinematicSelection.cc+("Signal_V42_V8", "glugluToX600ToHHTobbbb_8TeV_width1MeV_FASTSIM_PU", "PUWeight.root")'
root -l -b -q 'HbbHbb_KinematicSelection.cc+("Signal_V42_V8", "glugluToX700ToHHTobbbb_8TeV_width1MeV_FASTSIM_PU", "PUWeight.root")'
root -l -b -q 'HbbHbb_KinematicSelection.cc+("Signal_V42_V8", "glugluToX800ToHHTobbbb_8TeV_width1MeV_FASTSIM_PU", "PUWeight.root")'
